L3 Templates/temps/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("myapp.urls", namespace="myapp")),
]

L3 Templates/temps/myapp/urls.py
from django.urls import path
from .views import show_all_models, show_one_model, index, home, delete_model

app_name = 'myapp'

urlpatterns = [
    path('', index, name='index'),
    path('index/', home),
    path('models/', show_all_models, name='models'),
    path('models/<int:id>/', show_one_model, name='one_model'),
    path('models/<int:id>/delete', delete_model, name='delete_model'),
]

L3 Templates/temps/myapp/models.py
from django.db import models


class MyModel(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.name}: {self.created_at}'

L3 Templates/temps/myapp/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect

from .models import MyModel


def show_all_models(request: HttpRequest) -> HttpResponse:
    if request.method == 'POST':
        name = request.POST.get('name')
        if not name:
            name = 'Untitled'
        desc = request.POST.get('description')
        if not desc:
            desc = 'No description'
        MyModel.objects.create(name=name, description=desc)
        return redirect('myapp:models')
    all_models = MyModel.objects.all()
    context = {'models': all_models, 'title': 'Мои модели'}
    return render(request, 'myapp/models.html', context)


def show_one_model(request: HttpRequest, id: int) -> HttpResponse:
    if request.method == 'GET':
        model = MyModel.objects.get(id=id)
        context = {'model': model, 'title': model.name}
        return render(request, 'myapp/one_model.html', context)
    elif request.method == 'POST':
        model = MyModel.objects.get(id=id)
        model.name = request.POST.get('name', model.name)
        model.description = request.POST.get('description', model.description)
        model.save()
        return redirect('myapp:one_model', id)


def delete_model(request: HttpRequest, id: int) -> HttpResponse:
    model = MyModel.objects.get(id=id)
    model.delete()
    return redirect('myapp:models')


def index(request: HttpRequest) -> HttpResponse:
    class A:
        def __init__(self):
            self.a = 1

        def b(self):
            return 2

        def __str__(self):
            return 'A'

    context = {
        'title': 'Главная',
        'list': [1, 2, 3],
        'dict': {'a': 1, 'b': 2},
        'a': A(),
    }
    return render(request, 'myapp/index.html', context)


def home(request: HttpRequest) -> HttpResponse:
    return redirect('myapp:index')

L3 Templates/temps/myapp/templates/myapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT"
          crossorigin="anonymous">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    {% block head %}{% endblock %}
</head>
<body>
<header>
    {% include 'myapp/navbar.html' %}
</header>


{% block content %}{% endblock %}

<footer class="text-center">2025 (с) All rights reserved PythonRush</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO"
        crossorigin="anonymous"></script>
</body>
</html>

L3 Templates/temps/myapp/templates/myapp/edit_create_model_form.html
<div class="container">
    <form method="post" class="form">
        {% csrf_token %}
        <input type="text" class="form-control" name="name"
               placeholder="{{ model.name|default:'Название' }}">
        <input type="text" class="form-control" name="description"
               placeholder="{{ model.description|default:'Описание'}}">
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
</div>

L3 Templates/temps/myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}

{% block content %}
<p>{{ list }}</p>
<p>{{ dict }}</p>
<p>{{ dict.a }}</p>
<p>{{ list.0 }}</p>
<p>{{a}}</p>
<p>{{a.a}}</p>
<p>{{a.b}}</p>
{% endblock %}

L3 Templates/temps/myapp/templates/myapp/models.html
{% extends 'myapp/base.html' %}

{% block head %}{% endblock %}

{% block content %}
<div class="container d-flex flex-column">
    <h1>Все модели</h1>
    <div class="container">
        <h3>Добавить модель</h3>
        {% include 'myapp/edit_create_model_form.html' %}
    </div>
    <div class="container d-flex flex-column">

        {% if models.count == 0 %}
        <p>Пока нет моделей</p>
        {% else %}
        <p>Моделей: {{ models.count }}</p>
        {% for model in models %}
        <div class="container  d-flex flex-row">
            <div class="card" style="width: 25rem;">
                <div class="card-body">
                    <h5 class="card-title">{{ model.name }}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">
                        {{model.created_at}}
                    </h6>
                    <p class="card-text">
                        {{ model.description|truncatechars:15}}
                    </p>
                    <div class="container text-center">
                                <a href="{% url 'myapp:one_model' model.id %}"
                                   class="card-link">Детали</a>
                                <form method="delete"
                                      action="{% url 'myapp:delete_model' model.id  %}">
                                    {% csrf_token %}
                                    <button class="btn btn-outline-danger"
                                            type="submit">
                                        Удалить
                                    </button>
                                </form>

                        </div>

                    </div>
                </div>

            </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

L3 Templates/temps/myapp/templates/myapp/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarNav" aria-controls="navbarNav"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'myapp:index' %}">Главная</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'myapp:models' %}">Все модели</a>
            </li>
        </ul>
    </div>
</nav>

L3 Templates/temps/myapp/templates/myapp/one_model.html
{% extends 'myapp/base.html' %}

{% block content %}
<h1>Модель {{ model.name }}</h1>
<h2>Description : {{ model.description }}</h2>
<h2>Создана: {{ model.created_at|date:"Y-m-d H:i:s" }}</h2>
<form method="post" action="{% url 'myapp:delete_model' model.id %}">
    {% csrf_token %}
    <button type="submit">Удалить</button>
</form>
<div>
    <h3>Редактировать</h3>
    {% include 'myapp/edit_create_model_form.html' %}
</div>

{% endblock %}